### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by ghost** [JohnLaTwC/PyPowerShellXray#2]
Hi there,

Any idea why I'm seeing the error below please?

PS C:\PyPowerShellXray-master> .\psx.py .\script1.ps1
Traceback (most recent call last):
  File "C:\PyPowerShellXray-master\psx.py", line 87, in <module>
    from envi.archs.i386 import i386Disasm
  File "C:\vivisect-master\vivisect-master\envi\__init__.py", line 352
    print "%s needs to implement getOperValue!" % self.__class__.__name__
                                              ^
SyntaxError: Missing parentheses in call to 'print'
PS C:\PyPowerShellXray-master>

----

My python path environment variable is configured as follows:

pythonpath=C:\vivisect-master\vivisect-master

Thanks

**Comment by ghost** [comment]
Seems to be working using Python 2.7. Thanks
